# Generated by Django 3.2.4 on 2024-05-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210610_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='title',
            new_name='name',
        ),
    ]
