# Generated by Django 3.2.4 on 2024-05-22 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_title_collection_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='name',
            new_name='title',
        ),
    ]
