# Generated by Django 3.2.4 on 2024-05-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_name_collection_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='ph4one',
        ),
    ]
