# Generated by Django 3.2.4 on 2024-05-28 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20240527_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='ph4one',
            new_name='phone',
        ),
    ]
