# Generated by Django 4.2.16 on 2024-09-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_orderitem_product_alter_product_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='roduct',
            new_name='product',
        ),
    ]
