# Generated by Django 4.2.14 on 2024-07-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_cart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
    ]
